// GENERATED FILE.
// Source artifact:
//   contracts/out/CelerCircleBridgeFacet.sol/CelerCircleBridgeFacet.json
// Generated by:
//   python3 scripts/sync_lifi_abi.py

export const LIFI_CELER_CIRCLE_BRIDGE_ABI = [
  {
    "type": "function",
    "name": "startBridgeTokensViaCelerCircleBridge",
    "inputs": [
      {
        "name": "_bridgeData",
        "type": "tuple",
        "internalType": "struct ILiFi.BridgeData",
        "components": [
          {
            "name": "transactionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bridge",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "integrator",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "referrer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sendingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "destinationChainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hasSourceSwaps",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hasDestinationCall",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "_celerCircleData",
        "type": "tuple",
        "internalType": "struct CelerCircleBridgeFacet.CelerCircleData",
        "components": [
          {
            "name": "maxFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minFinalityThreshold",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
