// GENERATED FILE.
// Source artifact:
//   contracts/out/AcrossFacetV3.sol/AcrossFacetV3.json
// Generated by:
//   python3 scripts/sync_lifi_abi.py

export const LIFI_ACROSS_FACET_V3_ABI = [
  {
    "type": "function",
    "name": "startBridgeTokensViaAcrossV3",
    "inputs": [
      {
        "name": "_bridgeData",
        "type": "tuple",
        "internalType": "struct ILiFi.BridgeData",
        "components": [
          {
            "name": "transactionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bridge",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "integrator",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "referrer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sendingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "destinationChainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hasSourceSwaps",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hasDestinationCall",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "_acrossData",
        "type": "tuple",
        "internalType": "struct AcrossFacetV3.AcrossV3Data",
        "components": [
          {
            "name": "receiverAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "refundAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receivingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "outputAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "outputAmountPercent",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "exclusiveRelayer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteTimestamp",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "fillDeadline",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "exclusivityDeadline",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "message",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "swapAndStartBridgeTokensViaAcrossV3",
    "inputs": [
      {
        "name": "_bridgeData",
        "type": "tuple",
        "internalType": "struct ILiFi.BridgeData",
        "components": [
          {
            "name": "transactionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bridge",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "integrator",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "referrer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sendingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "destinationChainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hasSourceSwaps",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hasDestinationCall",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "_swapData",
        "type": "tuple[]",
        "internalType": "struct LibSwap.SwapData[]",
        "components": [
          {
            "name": "callTo",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "approveTo",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sendingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receivingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fromAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "callData",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "requiresDeposit",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "_acrossData",
        "type": "tuple",
        "internalType": "struct AcrossFacetV3.AcrossV3Data",
        "components": [
          {
            "name": "receiverAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "refundAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receivingAssetId",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "outputAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "outputAmountPercent",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "exclusiveRelayer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteTimestamp",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "fillDeadline",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "exclusivityDeadline",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "message",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  }
] as const;
