#!/usr/bin/env python3
"""
Sync pinned LiFi ABIs for frontend encoding.

Reads:
  contracts/out/AcrossFacetV3.sol/AcrossFacetV3.json
  contracts/out/CelerCircleBridgeFacet.sol/CelerCircleBridgeFacet.json
Writes:
  web/src/abi/lifiAcrossFacetV3.ts
  web/src/abi/lifiCelerCircleBridgeFacet.ts
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "contracts" / "out" / "AcrossFacetV3.sol" / "AcrossFacetV3.json"
OUT = ROOT / "web" / "src" / "abi" / "lifiAcrossFacetV3.ts"
NAMES = {
    "startBridgeTokensViaAcrossV3",
    "swapAndStartBridgeTokensViaAcrossV3",
}
CELER_ARTIFACT = ROOT / "contracts" / "out" / "CelerCircleBridgeFacet.sol" / "CelerCircleBridgeFacet.json"
CELER_OUT = ROOT / "web" / "src" / "abi" / "lifiCelerCircleBridgeFacet.ts"


def main() -> None:
    raw = json.loads(ARTIFACT.read_text())
    abi = [e for e in raw.get("abi", []) if e.get("type") == "function" and e.get("name") in NAMES]
    if len(abi) != 2:
        raise SystemExit(f"expected 2 ABI entries, got {len(abi)}")

    header = (
        "// GENERATED FILE.\n"
        "// Source artifact:\n"
        "//   contracts/out/AcrossFacetV3.sol/AcrossFacetV3.json\n"
        "// Generated by:\n"
        "//   python3 scripts/sync_lifi_abi.py\n\n"
    )
    body = "export const LIFI_ACROSS_FACET_V3_ABI = " + json.dumps(abi, indent=2) + " as const;\n"
    OUT.write_text(header + body)
    print(f"wrote {OUT}")

    celer_raw = json.loads(CELER_ARTIFACT.read_text())
    celer_abi = [
        e
        for e in celer_raw.get("abi", [])
        if e.get("type") == "function" and e.get("name") == "startBridgeTokensViaCelerCircleBridge"
    ]
    if len(celer_abi) != 1:
        raise SystemExit(f"expected 1 celer ABI entry, got {len(celer_abi)}")
    CELER_OUT.write_text(
        "// GENERATED FILE.\n"
        "// Source artifact:\n"
        "//   contracts/out/CelerCircleBridgeFacet.sol/CelerCircleBridgeFacet.json\n"
        "// Generated by:\n"
        "//   python3 scripts/sync_lifi_abi.py\n\n"
        + "export const LIFI_CELER_CIRCLE_BRIDGE_ABI = "
        + json.dumps(celer_abi, indent=2)
        + " as const;\n"
    )
    print(f"wrote {CELER_OUT}")


if __name__ == "__main__":
    main()
